services:
  db:
    image: postgres:16
    container_name: ams-postgres
    restart: always

    environment:
      POSTGRES_DB: ams_db
      POSTGRES_USER: ams_user
      POSTGRES_PASSWORD: ams_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - ams-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ams_user -d ams_db" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ams-app
    restart: always

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ams_db
      SPRING_DATASOURCE_USERNAME: ams_user
      SPRING_DATASOURCE_PASSWORD: ams_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

    networks:
      - ams-network


volumes:
  postgres_data:


networks:
  ams-network:
    driver: bridge